In [9]:
import numpy as np

class Adam:
    def __init__(self, num_features, lr=0.01, betas=(0.9, 0.99), eps=1e-6):
        shape = num_features

        self.lr = lr
        self.beta_1, self.beta_2 = betas
        self.eps = eps
        self.v = np.zeros(shape)
        self.g = np.zeros(shape)
        self.v_hat = np.zeros(shape)
        self.g_hat = np.zeros(shape)

    def step(self, w, dLdw, t):
        self.v = self.beta_1*self.v + (1 - self.beta_1)*dLdw
        self.g = self.beta_2*self.g + (1 - self.beta_2)*dLdw**2
        self.v_hat = self.v/(1 - self.beta_1**(t + 1))
        self.g_hat = self.g/(1 - self.beta_2**(t + 1))
        return np.array(w - self.lr/np.sqrt(self.g_hat + self.eps)*self.v_hat)

def read_matrix(n_rows, dtype=float):
    return np.array([list(map(dtype, input().split())) for _ in range(n_rows)]).astype(float)

def print_matrix(matrix):
    for row in matrix:
        print(' '.join(map(str, row)))

def solution():
    iterations, num_features = 3, 4
    lr, beta_1, beta_2, eps = 0.01, 0.9, 0.99, 0.000001
    w = np.array([0.037, 0.327, -1.897, 0.57])
    dLdw = np.array([[1.344, 0.41, 0.892, 1.207],
                    [-1.04, -0.732, -1.084, 1.682],
                    [1.41, -1.805, 1.146, 1.063]])
    print(dLdw)

    optimizer = Adam(num_features, lr, (beta_1, beta_2), eps)

    for i in range(iterations):
        w = optimizer.step(w, dLdw[i], i)
    print(w)

    print_matrix(w.round(3))

solution()

[[ 1.344  0.41   0.892  1.207]
 [-1.04  -0.732 -1.084  1.682]
 [ 1.41  -1.805  1.146  1.063]]
[ 0.02173466  0.3270343  -1.90865647  0.54029031]


TypeError: 'numpy.float64' object is not iterable

In [8]:
np.array([ 0.02173466,  0.3270343,  -1.90865647,  0.54029031]).round(3)

array([ 0.022,  0.327, -1.909,  0.54 ])

In [16]:
import numpy as np
x = np.array([[ 0,  1,  3,  4,  0],
              [ 0,  3, -1,  1,  0]])
w = np.array([[ 2,  1, -1],
              [-1,  2,  3]])
res = 0
for i in range(w.shape[1]):
    res += np.sum(x[:, i:i+3]*w)
print(res)

13


In [12]:
x[:, 0:3]*w

array([[ 0,  1, -3],
       [ 0,  6, -3]])

In [78]:
x1 = np.array([[7],
              [-4]])
x2 = np.array([[0.5],
              [3]])
x3 = np.array([[10],
              [2]])
waa = np.array([[0,  1, 0],
              [2,  0,  -1],
               [0, 1, 3]])
wax = np.array([[0,  2],
              [1, 0],
               [0, 4]])
ba = np.array([[-1], [1], [0]])
a0 = np.array([[0], [0], [0]])

In [79]:
relu = lambda x: max(0, x)

In [80]:
a1 = np.dot(waa, a0) + np.dot(wax, x1) + ba
a1



array([[ -9],
       [  8],
       [-16]])

In [81]:
a1 = np.array([[0], [8], [0]])

In [83]:
a2 = np.dot(waa, a1) + np.dot(wax, x2) + ba
np.sum(a2)

34.5

In [63]:
list(map(relu, a))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [31]:
x1.shape

(3, 1)

In [33]:
x1 = np.array([[7],
              [-4]])
x1

array([[ 7],
       [-4]])

In [55]:
f = lambda x: 2 if x ** 2

In [56]:
f(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()