In [1]:
import numpy as np


class Conv1d:

    def __init__(self, in_channels, out_channels, kernel_size, padding='same', activation='relu'):
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.padding = padding
        self.activation = activation

        self.W, self.biases = self.init_weight_matrix()

    def init_weight_matrix(self,):
        np.random.seed(1)
        W = np.random.uniform(size=(self.in_channels, self.kernel_size, self.out_channels))
        biases = np.random.uniform(size=(1, self.out_channels))
        #print('w=',W)
        #print(W.shape)
        #print('b=', biases)
        return W, biases

    def forward(self, x):
        padding = (self.kernel_size - 1)//2
        x_with_padding = np.pad(x, ((0, 0), (padding, padding)), mode='constant') # добавляем паддинг
        res = []
        for i in range(self.out_channels):
            a = []
            for j in range(x.shape[1]):
                z = np.sum(self.W[:,:, i]*x_with_padding[:, j:j+self.kernel_size]) + self.biases[0][i]
                a.append(z if z > 0 else 0) # применяем ReLU
            res.append(a) # добавляем выходной одномерный вектор
        return np.array(res)
            
                #print(np.sum(W[0,:,i]*x_with_padding[0, j:j+self.kernel_size] + self.W[1,:,i]*x_with_padding[1, j:j+self.kernel_size]) + self.biases[0][i])
        #z = #np.array([x_with_padding[:,i:i+3].T*self.W for i in range(x.shape[0])])
        #n = x.shape[1]
        
        #print([[x_with_padding[:,i:i+n]*self.W] for i in range(n)])
#         for i in range(3):
#             res += np.sum((x[:,i:i+3]*w))
        #pass

def read_matrix(n_rows, dtype=float):
    return np.array([list(map(dtype, input().split())) for _ in range(n_rows)])

def print_matrix(matrix):
    for row in matrix:
        print(' '.join(map(str, row)))

def solution():
    in_channels, out_channels, kernel_size = 30, 2, 15
    input_vectors = np.arange(30*5)#np.array([[10.0, -10.0, 10.0], 
                              #[5.0, 15.0, -5.0]])
    
    input_vectors.resize(30, 5)
    conv = Conv1d(in_channels, out_channels, kernel_size)
    output = conv.forward(input_vectors).round(3)
    print_matrix(output)

solution()

5980.732 5983.56 5942.288 5905.956 5772.503
5242.853 5199.431 5398.825 5454.699 5520.372


In [2]:
import numpy as np
x = np.array([[ 0,  1,  3,  4,  0],
              [ 0,  3, -1,  1,  0]])
w = np.array([[ 2,  1, -1],
              [-1,  2,  3]])
res = 0
for i in range(3):
    print(x[:,i:i+3]*w)

[[ 0  1 -3]
 [ 0  6 -3]]
[[ 2  3 -4]
 [-3 -2  3]]
[[6 4 0]
 [1 2 0]]


In [3]:
np.array([[0] for i in range(3)])

array([[0],
       [0],
       [0]])

In [4]:
x  = np.array([[10.0, -10.0, 10.0], 
               [5.0, 15.0, -5.0]])
np.random.seed(1)
W = np.random.uniform(size=(2, 3, 2))
b = np.random.uniform(size=(1, 2))

In [5]:
x_ = np.pad(x, ((0, 0), (1, 1)), mode='constant')
x_

array([[  0.,  10., -10.,  10.,   0.],
       [  0.,   5.,  15.,  -5.,   0.]])

In [6]:
W

array([[[4.17022005e-01, 7.20324493e-01],
        [1.14374817e-04, 3.02332573e-01],
        [1.46755891e-01, 9.23385948e-02]],

       [[1.86260211e-01, 3.45560727e-01],
        [3.96767474e-01, 5.38816734e-01],
        [4.19194514e-01, 6.85219500e-01]]])

In [14]:
(np.sum(W[0,:,1]*x_[0, 0:3] + W[1,:,1]*x_[1, 0:3]) + b[0][1]).round(3)

15.95

In [7]:
W[:,:, 1]

array([[0.72032449, 0.30233257, 0.09233859],
       [0.34556073, 0.53881673, 0.6852195 ]])

In [9]:
np.sum(x_[:, 2:5]*W[0, 0:3, :].T) + b[0][0]

5.328580489352399

In [13]:
# шифр разгадан!
(np.sum(W[0,:,1]*x_[0, 0:3] + W[1,:,1]*x_[1, 0:3]) + b[0][1]).round(3)

15.95

In [7]:
a = np.arange(30)
a.resize(2, 15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [30]:
W@x_[:, 0:3]

array([[[ 0.        ,  7.77184251,  6.63464735],
        [ 0.        ,  1.51280661,  4.53384484],
        [ 0.        ,  1.92925188, -0.08247999]],

       [[ 0.        ,  3.59040575,  3.32080879],
        [ 0.        ,  6.66175841,  4.11457627],
        [ 0.        ,  7.61804265,  6.08634736]]])

In [28]:
x_[:, 0:3]

array([[  0.,  10., -10.],
       [  0.,   5.,  15.]])

In [6]:
x_[:, 0:3]*W[0].T

array([[ 0.00000000e+00,  1.14374817e-03, -1.46755891e+00],
       [ 0.00000000e+00,  1.51166286e+00,  1.38507892e+00]])

In [61]:
W[1, 0:3, :].T

array([[0.30233257, 0.14675589, 0.09233859]])

In [15]:
x_[0, 0:3]

array([  0.,  10., -10.])

In [21]:
3.02332573e-01

0.302332573

In [26]:
W[0]

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02]])