In [87]:
import numpy as np


class Conv2d:

    def __init__(
        self, in_channels, out_channels, kernel_size_h, kernel_size_w, padding=0, stride=1
    ):
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size_h = kernel_size_h
        self.kernel_size_w = kernel_size_w
        self.padding = padding
        self.stride = stride

        self.W, self.biases = self.init_weight_matrix()

    def init_weight_matrix(self,):
        np.random.seed(1)
        W = np.random.uniform(size=(
            self.in_channels, self.kernel_size_h, self.kernel_size_w, self.out_channels
        ))
        biases = np.random.uniform(size=(1, self.out_channels))
        return W, biases

    def forward(self, x): 
        x_with_padding = [[] for i in range(self.in_channels)]
        for i in range(self.in_channels):
            x_with_padding[i] = np.pad(x[i], ((self.padding, self.padding), (self.padding, self.padding)), mode='constant')
        x_with_padding = np.array(x_with_padding)
        
        input_height = x.shape[1]
        input_width = x.shape[2]
        output_height = int(np.floor((input_height - self.kernel_size_h + self.padding*2 + self.stride)/self.stride))
        output_width = int(np.floor((input_width - self.kernel_size_w + self.padding*2 + self.stride)/self.stride))
        np_final_output = np.zeros([self.out_channels, output_height, output_width])
        for output in range(self.out_channels):
            for input in range(self.in_channels):
                for i in range(output_height):
                    for j in range(output_width):
                        filter_sum = 0
                        for m in range(self.kernel_size_h):
                            for n in range(self.kernel_size_w):
                                np_final_output[output][i][j] += x_with_padding[input][i*self.stride + m][j*self.stride + n] * \
                                                                        self.W[input][m][n][output]
                        if input == self.in_channels - 1:
                            np_final_output[output][i][j] += self.biases[0][output]
        return np_final_output



def read_matrix(in_channels, h, w, dtype=float):
    return np.array([list(map(dtype, input().split())) 
                     for _ in range(in_channels * h)]).reshape(in_channels, h, w)

def print_matrix(matrix):
    for channel in matrix:
        for row in channel:
            print(' '.join(map(str, row)))

def solution():
    in_channels, out_channels, kernel_size_h, kernel_size_w, h, w, padding, stride = 2, 3, 2, 2, 3, 4, 0, 1
    input_image = np.array([[1.0, 1.0, 1.0, 1.0], 
                            [1.0, 0.0, 2.0, 1.0], 
                            [1.0, 2.0, 0.0, 1.0], 
                            [5.0, 7.0, 4.0, 5.0], 
                            [3.0, 6.0, 5.0, 5.0], 
                            [8.0, 4.0, 6.0, 3.0]]).reshape(in_channels, h, w)
    #print(input_image)
    conv = Conv2d(in_channels, out_channels, kernel_size_h, kernel_size_w, padding, stride)
    output = conv.forward(input_image).round(3)
    print_matrix(output)

solution()

13.728 12.47 12.22
12.19 12.804 10.673
11.894 13.172 11.029
10.776 11.907 11.507
11.178 12.24 12.025
14.462 11.378 10.675


In [9]:
np.zeros([4, 2]) + 2

array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [66]:
in_channels, out_channels, kernel_size_h, kernel_size_w, h, w, padding, stride = 2, 3, 2, 2, 3, 4, 0, 1
np.random.seed(1)
W = np.random.uniform(size=(
            in_channels, kernel_size_h, kernel_size_w, out_channels
        ))
biases = np.random.uniform(size=(1, out_channels))
W

array([[[[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
         [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]],

        [[1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
         [5.38816734e-01, 4.19194514e-01, 6.85219500e-01]]],


       [[[2.04452250e-01, 8.78117436e-01, 2.73875932e-02],
         [6.70467510e-01, 4.17304802e-01, 5.58689828e-01]],

        [[1.40386939e-01, 1.98101489e-01, 8.00744569e-01],
         [9.68261576e-01, 3.13424178e-01, 6.92322616e-01]]]])

In [67]:
X = np.array([[1.0, 1.0, 1.0, 1.0], 
                            [1.0, 0.0, 2.0, 1.0], 
                            [1.0, 2.0, 0.0, 1.0], 
                            [5.0, 7.0, 4.0, 5.0], 
                            [3.0, 6.0, 5.0, 5.0], 
                            [8.0, 4.0, 6.0, 3.0]]).reshape(in_channels, h, w)

In [82]:

#import tensorflow as tf
import numpy as np
 
batch_size = 1
 
input_height = h
input_width = w
 
filter_height = kernel_size_h
filter_width = kernel_size_w
 
output_height = int(np.floor((input_height - filter_height + padding + stride)/stride))
output_width = int(np.floor((input_width - filter_width + padding + stride)/stride))
 
input_channel = in_channels
output_channel = out_channels
 
# [batch, in_height, in_width, in_channels]
np_input_arg = np.ones([batch_size, input_height, input_width, input_channel])
# [filter_height, filter_width, in_channels, out_channels]
np_filter_arg = np.ones([filter_height, filter_width, input_channel, output_channel])
np_biases = np.ones([batch_size,1,1,output_channel])
 
np_final_output = np.zeros([output_channel, output_height, output_width])
 
# manual convolution
for output in range(output_channel):
    for input in range(input_channel):
        for i in range(output_height):
            for j in range(output_width):
                # a filter window
                filter_sum = 0
                # convolution operation: [i,i+1,i+2] * [j,j+1,j+2]   [3] * [3] = [9]
                for m in range(filter_height):
                    for n in range(filter_width):
                        np_final_output[output][i][j] += X[input][i*stride + m][j*stride + n] * \
                                                                W[input][m][n][output]
                if input == input_channel - 1:
                    np_final_output[output][i][j] += biases[0][output]
                # print('np_final_output[{0}][{1}][{2}][{3}]:{4}'.format(batch,i,j,output, np_final_output[batch][i][j][output]))
print('np_final_output:', np_final_output)


np_final_output: [[[13.72826803 12.4700425  12.22047001]
  [12.18960846 12.80374298 10.67328763]]

 [[11.89381811 13.17184717 11.02862511]
  [10.77557066 11.90741955 11.50719872]]

 [[11.17820082 12.24048914 12.02458707]
  [14.46191382 11.37794502 10.67465342]]]


In [77]:
output_width

3.0

In [55]:
np_input_arg

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [71]:
np.zeros([output_channel, output_height, output_width])

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [81]:
for i in range(0, 10, 2):
    print(i)

0
2
4
6
8


In [86]:
biases

array([[0.87638915, 0.89460666, 0.08504421]])