In [2]:
# 1.0 0.0 2.5 2.0 2.0 1.5 3.5

In [6]:
import numpy as np

def mse(y):
    n = len(y)
    if n == 0:
        return 0
    y_mean = np.mean(y)
    return np.sum((y - y_mean)**2)/n

def Q(l, r, full_mse):
    l_n  = len(l)
    r_n = len(r)
    n = l_n + r_n
    return full_mse - (l_n/n*mse(l) + r_n/n*mse(r))

def find_splits(X, column):
    X_unique = np.unique(X[:, column])
    split_values = np.empty(X_unique.shape[0] - 1)
    for i in range(1, X_unique.shape[0]):
        average = (X_unique[i - 1] + X_unique[i]) / 2
        split_values[i - 1] = average
    return split_values

def decision_stump(X, y):

    best_Q = None 
    best_j = None  # индекс признака по которому производился лучший сплит
    best_t = None  # порог с котором сравнивается признак
    best_left_ids = None # вектор со значениями True для объектов в левом поддереве, остальные False
    best_right_ids = None # вектор со значениями True для объектов в правом поддереве, остальные False
    y_preds_left = None # предсказание в левом поддерева
    y_preds_right = None # предсказание в правом поддерева
    
    full_mse = mse(y)
    features = X.shape[1]
    for j in range(features):
        split_values = find_splits(X, j)
        for t in split_values:
            left_mask = X[:, j] <= t
            right_mask = X[:, j] > t
            left_y, right_y = y[left_mask], y[right_mask]
            Q_cur = Q(left_y, right_y, full_mse)
            if best_Q is None or Q_cur > best_Q:
                best_Q = Q_cur
                best_j = j
                best_t = t
                best_left_ids = left_mask
                best_right_ids = right_mask
                y_preds_left = np.mean(left_y)
                y_preds_right = np.mean(right_y)
    result = [
        best_Q,
        best_j,
        best_t,
        best_left_ids.sum(),
        best_right_ids.sum(),
        y_preds_left,
        y_preds_right
    ]
    return result

def read_input():
    n, m = 4, 2
    x_train = np.array([[1.0, 0.0], [2.0, 0.0], [3.0, 0.0], [4.0, 0.0]])
    y_train = np.array([1.0, 2.0, 3.0, 4.0])
    return x_train, y_train

def solution():
    X, y = read_input()
    result = decision_stump(X, y)
    result = np.round(result, 2)
    output = ' '.join(map(str, result))
    print(output)

solution()

1.0 0.0 2.5 2.0 2.0 1.5 3.5


In [ ]:
# 1.0 0.0 2.5 2.0 2.0 1.5 3.5

In [5]:
import numpy as np
a = np.array([[1], [2], [3], [4], [5]])
mask = np.array([True, False, False, True, True])
a[mask]

array([[1],
       [4],
       [5]])

In [1]:
# неудавшийся вариант
import numpy as np

def mse(y):
    n = len(y)
    if n == 0:
        return 0
    y_mean = np.mean(y)
    return np.sum((y - y_mean)**2)/n

def Q(l, r, full):
    l_n  = len(l)
    r_n = len(r)
    n = l_n + r_n
    return mse(full) - (l_n/n*mse(l) + r_n/n*mse(r))

def decision_stump(X, y):

    best_Q = -1  
    best_j = -1  # индекс признака по которому производился лучший сплит
    best_t = -1  # порог с котором сравнивается признак
    best_left_ids = [] # вектор со значениями True для объектов в левом поддереве, остальные False
    best_right_ids = [] # вектор со значениями True для объектов в правом поддереве, остальные False
    y_preds_left = -1 # предсказание в левом поддерева
    y_preds_right = -1 # предсказание в правом поддерева
    
    features = X.shape[1]
    for j in range(features):
        t_min = min(X[:, j])
        for i, t in enumerate(X[:, j]):
            l_arr = np.array([y_ for x, y_ in zip(X[:, j], y) if x < t])
            r_arr = np.array([y_ for x, y_ in zip(X[:, j], y) if x >= t])
            Q_cur = Q(l_arr, r_arr, y)
            if Q_cur > best_Q:
                best_Q = Q_cur
                best_j = j
                best_t = (t + X[i - 1][j])/2 if t > t_min else t
                best_left_ids = np.array([True if y_ in l_arr else False for y_ in y])
                best_right_ids = np.array([True if y_ in r_arr else False for y_ in y])
                y_preds_left = np.mean(l_arr) if len(l_arr) > 0 else 0
                y_preds_right = np.mean(r_arr) if len(r_arr) > 0 else 0
    result = [
        best_Q,
        best_j,
        best_t,
        best_left_ids.sum(),
        best_right_ids.sum(),
        y_preds_left,
        y_preds_right
    ]
    return result

def read_input():
    n, m = 4, 2
    x_train = np.array([[1.0, 0.0], [2.0, 0.0], [3.0, 0.0], [4.0, 0.0]])
    y_train = np.array([1.0, 2.0, 3.0, 4.0])
    return x_train, y_train

def solution():
    X, y = read_input()
    result = decision_stump(X, y)
    print(result)
    result = np.round(result, 2)
    output = ' '.join(map(str, result))
    print(output)

solution()

[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1.]
[2. 3. 4.]
[1. 2. 3. 4.]
[1. 2.]
[3. 4.]
[1. 2. 3. 4.]
[1. 2. 3.]
[4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1.0, 0, 2.5, 2, 2, 1.5, 3.5]
1.0 0.0 2.5 2.0 2.0 1.5 3.5
